# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Pre-Production deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ['pre-production']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn validate
      - run: yarn test
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          --git-branch=${{ github.ref_name }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run:
          echo "DEPLOYED_URL=$( vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} )" >>
          $GITHUB_ENV
      - name: Alias to pre production domain
        run:
          vercel alias set $DEPLOYED_URL tetraimpacts-web-app-pre-production.vercel.app --token=${{
          secrets.VERCEL_TOKEN }} --scope tetra-impacts
